# Generated by Django 3.1 on 2020-09-29 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatimage',
            name='chat',
        ),
    ]
