# Generated by Django 3.1 on 2020-09-10 23:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('fuelType', models.CharField(max_length=50)),
                ('carMake', models.CharField(max_length=50)),
                ('carModel', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=50)),
                ('carYear', models.IntegerField()),
                ('carMilage', models.IntegerField()),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('image1', models.ImageField(blank=True, default='/images/carDefault.jpg', null=True, upload_to='', verbose_name='uploaded images')),
                ('image2', models.ImageField(blank=True, default='/images/carDefault.jpg', null=True, upload_to='', verbose_name='uploaded images')),
                ('image3', models.ImageField(blank=True, default='/images/carDefault.jpg', null=True, upload_to='', verbose_name='uploaded images')),
                ('image4', models.ImageField(blank=True, default='/images/carDefault.jpg', null=True, upload_to='', verbose_name='uploaded images')),
                ('image5', models.ImageField(blank=True, default='/images/carDefault.jpg', null=True, upload_to='', verbose_name='uploaded images')),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('checkin_date', models.DateField(blank=True, null=True)),
                ('checkout_date', models.DateField(blank=True, null=True)),
                ('period', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('carId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_reserved', to='cars.cars')),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_car_reserving', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('review', models.CharField(blank=True, max_length=50, null=True)),
                ('carId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_rated', to='cars.cars')),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_car_rating', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
